export const FORM_ACTION = {
  FILL_FORM: 'FILL_FORM',
  ADD_VALIDATION_ERROR_MSG: 'ADD_VALIDATION_ERROR_MSG',
  ADD_LOAD_FORM: 'ADD_LOAD_FORM',
  DELETE_LOAD_FORM: 'DELETE_LOAD_FORM',
  // COPY_FILL_FORM
};

export const ORDER_ACTION = {
  GET_ORDER_REQUEST: 'GET_ORDER_REQUEST',
  GET_ORDER_SUCCESS: 'GET_ORDER_SUCCESS',
  GET_ORDER_FAILURE: 'GET_ORDER_FAILURE',
  POST_ORDER_REQUEST: 'POST_ORDER_REQUEST',
  POST_ORDER_SUCCESS: 'POST_ORDER_SUCCESS',
  POST_ORDER_FAILURE: 'POST_ORDER_FAILURE',
  DELETE_ORDER_REQUEST: 'DELETE_ORDER_REQUEST',
  DELETE_ORDER_SUCCESS: 'DELETE_ORDER_SUCCESS',
  DELETE_ORDER_FAILURE: 'DELETE_ORDER_FAILURE',
};
