export const INPUT_CONST = {
  // BASE_FORM
  BASE_NAME: 'BASE_NAME',
  BASE_PHONE_NUMBER: 'BASE_PHONE_NUMBER',
  BASE_FROM_DATE: 'BASE_FROM_DATE',
  BASE_TO_DATE: 'BASE_TO_DATE',
  BASE_ITEM: 'BASE_ITEM',
  BASE_ITEM_DETAIL: 'BASE_ITEM_DETAIL',
  BASE_SUPPLY: 'BASE_SUPPLY',
  BASE_SUPPLY_DETAIL: 'BASE_SUPPLY_DETAIL',
  BASE_ADDRESS: 'BASE_ADDRESS',

  // LOAD_FORM
  LOAD_NAME: 'LOAD_NAME',
  LOAD_DATE: 'LOAD_DATE',
  LOAD_ADDRESS: 'LOAD_ADDRESS',
};
